# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from Library_Window import Ui_Figure_Library
from LogChat_Window import Ui_Chat
from Rule_Window import Ui_Rule
import game_logic

class Ui_PoDuRedux(object):
    def openLibrary(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Figure_Library()
        self.ui.setupUi(self.window)
        self.window.show()
    def openChat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Chat()
        self.ui.setupUi(self.window)
        self.window.show()
    def openRule(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Rule()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, PoDuRedux):
        PoDuRedux.setObjectName("PoDuRedux")
        PoDuRedux.resize(1024, 1024)
        PoDuRedux.setMouseTracking(True)
        PoDuRedux.setAutoFillBackground(False)
        PoDuRedux.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(PoDuRedux)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget{background-image: url(\'/images/board/backgrounds/Lapis.png\')}")
        self.centralwidget.setObjectName("centralwidget")
        self.Player1Team = QtWidgets.QComboBox(self.centralwidget)
        self.Player1Team.setGeometry(QtCore.QRect(20, 500, 211, 22))
        self.Player1Team.setObjectName("Player1Team")
        self.Player1Team.addItem("")
        self.Player2Team = QtWidgets.QComboBox(self.centralwidget)
        self.Player2Team.setGeometry(QtCore.QRect(790, 500, 221, 22))
        self.Player2Team.setObjectName("Player2Team")
        self.Player2Team.addItem("")
        self.Player2Ability = QtWidgets.QPushButton(self.centralwidget)
        self.Player2Ability.setEnabled(False)
        self.Player2Ability.setGeometry(QtCore.QRect(790, 580, 61, 28))
        self.Player2Ability.setObjectName("Player2Ability")
        self.Player1ZGauge = QtWidgets.QProgressBar(self.centralwidget)
        self.Player1ZGauge.setGeometry(QtCore.QRect(20, 540, 211, 23))
        self.Player1ZGauge.setAutoFillBackground(True)
        self.Player1ZGauge.setMaximum(36)
        self.Player1ZGauge.setProperty("value", 0)
        self.Player1ZGauge.setAlignment(QtCore.Qt.AlignCenter)
        self.Player1ZGauge.setTextVisible(True)
        self.Player1ZGauge.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Player1ZGauge.setObjectName("Player1ZGauge")
        self.Player2ZGauge = QtWidgets.QProgressBar(self.centralwidget)
        self.Player2ZGauge.setGeometry(QtCore.QRect(790, 540, 221, 23))
        self.Player2ZGauge.setAutoFillBackground(True)
        self.Player2ZGauge.setStyleSheet("")
        self.Player2ZGauge.setMaximum(36)
        self.Player2ZGauge.setProperty("value", 0)
        self.Player2ZGauge.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Player2ZGauge.setTextVisible(True)
        self.Player2ZGauge.setInvertedAppearance(True)
        self.Player2ZGauge.setObjectName("Player2ZGauge")
        self.Player1Ability = QtWidgets.QPushButton(self.centralwidget)
        self.Player1Ability.setEnabled(False)
        self.Player1Ability.setGeometry(QtCore.QRect(20, 580, 61, 28))
        self.Player1Ability.setObjectName("Player1Ability")
        self.Player1End = QtWidgets.QPushButton(self.centralwidget)
        self.Player1End.setEnabled(False)
        self.Player1End.setGeometry(QtCore.QRect(172, 580, 61, 28))
        self.Player1End.setObjectName("Player1End")
        self.Player2End = QtWidgets.QPushButton(self.centralwidget)
        self.Player2End.setEnabled(False)
        self.Player2End.setGeometry(QtCore.QRect(942, 580, 71, 28))
        self.Player2End.setObjectName("Player2End")
        self.Player1ZMove = QtWidgets.QPushButton(self.centralwidget)
        self.Player1ZMove.setEnabled(False)
        self.Player1ZMove.setGeometry(QtCore.QRect(90, 580, 71, 28))
        self.Player1ZMove.setObjectName("Player1ZMove")
        self.Player2ZMove = QtWidgets.QPushButton(self.centralwidget)
        self.Player2ZMove.setEnabled(False)
        self.Player2ZMove.setGeometry(QtCore.QRect(860, 580, 71, 28))
        self.Player2ZMove.setObjectName("Player2ZMove")
        self.board_overlay3v3 = QtWidgets.QLabel(self.centralwidget)
        self.board_overlay3v3.setEnabled(True)
        self.board_overlay3v3.setGeometry(QtCore.QRect(0, 0, 1031, 1011))
        self.board_overlay3v3.setText("")
        self.board_overlay3v3.setPixmap(QtGui.QPixmap("images/board/overlays/dueloverlay3v3.png"))
        self.board_overlay3v3.setObjectName("board_overlay3v3")
        self.board_overlay = QtWidgets.QLabel(self.centralwidget)
        self.board_overlay.setEnabled(True)
        self.board_overlay.setGeometry(QtCore.QRect(0, 0, 1031, 1011))
        self.board_overlay.setMouseTracking(False)
        self.board_overlay.setStyleSheet("")
        self.board_overlay.setText("")
        self.board_overlay.setPixmap(QtGui.QPixmap("images/board/overlays/dueloverlay.png"))
        self.board_overlay.setObjectName("board_overlay")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setEnabled(True)
        self.background.setGeometry(QtCore.QRect(0, 0, 1326, 1056))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("images/board/backgrounds/Lapis.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.BlueForfeitButton = QtWidgets.QPushButton(self.centralwidget)
        self.BlueForfeitButton.setGeometry(QtCore.QRect(170, 960, 93, 28))
        self.BlueForfeitButton.setObjectName("BlueForfeitButton")
        self.RedForfeitButton = QtWidgets.QPushButton(self.centralwidget)
        self.RedForfeitButton.setGeometry(QtCore.QRect(770, 960, 93, 28))
        self.RedForfeitButton.setObjectName("RedForfeitButton")
        self.boardA1 = QtWidgets.QPushButton(self.centralwidget)
        self.boardA1.setGeometry(QtCore.QRect(257, 689, 70, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardA1.sizePolicy().hasHeightForWidth())
        self.boardA1.setSizePolicy(sizePolicy)
        self.boardA1.setAutoFillBackground(False)
        self.boardA1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardA1.setText("")
        self.boardA1.setObjectName("boardA1")
        self.player1Eliminated1 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Eliminated1.setGeometry(QtCore.QRect(91, 708, 70, 70))
        self.player1Eliminated1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Eliminated1.setText("")
        self.player1Eliminated1.setObjectName("player1Eliminated1")
        self.player1Eliminated3 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Eliminated3.setGeometry(QtCore.QRect(91, 798, 70, 70))
        self.player1Eliminated3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Eliminated3.setText("")
        self.player1Eliminated3.setObjectName("player1Eliminated3")
        self.player1Eliminated5 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Eliminated5.setGeometry(QtCore.QRect(91, 883, 70, 70))
        self.player1Eliminated5.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Eliminated5.setText("")
        self.player1Eliminated5.setObjectName("player1Eliminated5")
        self.player1Eliminated2 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Eliminated2.setGeometry(QtCore.QRect(15, 751, 70, 70))
        self.player1Eliminated2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Eliminated2.setText("")
        self.player1Eliminated2.setObjectName("player1Eliminated2")
        self.player1Eliminated4 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Eliminated4.setGeometry(QtCore.QRect(16, 841, 70, 70))
        self.player1Eliminated4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Eliminated4.setText("")
        self.player1Eliminated4.setObjectName("player1Eliminated4")
        self.player1Eliminated6 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Eliminated6.setGeometry(QtCore.QRect(17, 930, 70, 70))
        self.player1Eliminated6.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Eliminated6.setText("")
        self.player1Eliminated6.setObjectName("player1Eliminated6")
        self.player1Bench1 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Bench1.setGeometry(QtCore.QRect(277, 801, 70, 70))
        self.player1Bench1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
f"    background-image: url(/images/sprites/{player_1_team.pokemon1['spritefile']})"
"}")
        self.player1Bench1.setText("")
        self.player1Bench1.setObjectName("player1Bench1")
        self.player1Bench4 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Bench4.setGeometry(QtCore.QRect(327, 875, 70, 70))
        self.player1Bench4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Bench4.setText("")
        self.player1Bench4.setObjectName("player1Bench4")
        self.player1Bench2 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Bench2.setGeometry(QtCore.QRect(377, 801, 70, 70))
        self.player1Bench2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Bench2.setText("")
        self.player1Bench2.setObjectName("player1Bench2")
        self.player1Bench5 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Bench5.setGeometry(QtCore.QRect(428, 874, 70, 70))
        self.player1Bench5.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Bench5.setText("")
        self.player1Bench5.setObjectName("player1Bench5")
        self.player1Bench3 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Bench3.setGeometry(QtCore.QRect(478, 801, 70, 70))
        self.player1Bench3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Bench3.setText("")
        self.player1Bench3.setObjectName("player1Bench3")
        self.player1US1 = QtWidgets.QPushButton(self.centralwidget)
        self.player1US1.setGeometry(QtCore.QRect(864, 708, 70, 70))
        self.player1US1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1US1.setText("")
        self.player1US1.setObjectName("player1US1")
        self.player1US2 = QtWidgets.QPushButton(self.centralwidget)
        self.player1US2.setGeometry(QtCore.QRect(939, 751, 70, 70))
        self.player1US2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1US2.setText("")
        self.player1US2.setObjectName("player1US2")
        self.player1US3 = QtWidgets.QPushButton(self.centralwidget)
        self.player1US3.setGeometry(QtCore.QRect(863, 798, 70, 70))
        self.player1US3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1US3.setText("")
        self.player1US3.setObjectName("player1US3")
        self.player1US4 = QtWidgets.QPushButton(self.centralwidget)
        self.player1US4.setGeometry(QtCore.QRect(939, 841, 70, 70))
        self.player1US4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1US4.setText("")
        self.player1US4.setObjectName("player1US4")
        self.player1US5 = QtWidgets.QPushButton(self.centralwidget)
        self.player1US5.setGeometry(QtCore.QRect(863, 884, 70, 70))
        self.player1US5.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1US5.setText("")
        self.player1US5.setObjectName("player1US5")
        self.player1US6 = QtWidgets.QPushButton(self.centralwidget)
        self.player1US6.setGeometry(QtCore.QRect(939, 929, 70, 70))
        self.player1US6.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1US6.setText("")
        self.player1US6.setObjectName("player1US6")
        self.player2Eliminated1 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Eliminated1.setGeometry(QtCore.QRect(863, 233, 70, 70))
        self.player2Eliminated1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Eliminated1.setText("")
        self.player2Eliminated1.setObjectName("player2Eliminated1")
        self.player2Eliminated2 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Eliminated2.setGeometry(QtCore.QRect(937, 188, 70, 70))
        self.player2Eliminated2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Eliminated2.setText("")
        self.player2Eliminated2.setObjectName("player2Eliminated2")
        self.player2Eliminated3 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Eliminated3.setGeometry(QtCore.QRect(862, 142, 70, 70))
        self.player2Eliminated3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Eliminated3.setText("")
        self.player2Eliminated3.setObjectName("player2Eliminated3")
        self.player2Eliminated5 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Eliminated5.setGeometry(QtCore.QRect(863, 55, 70, 70))
        self.player2Eliminated5.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Eliminated5.setText("")
        self.player2Eliminated5.setObjectName("player2Eliminated5")
        self.player2Eliminated6 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Eliminated6.setGeometry(QtCore.QRect(937, 11, 70, 70))
        self.player2Eliminated6.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Eliminated6.setText("")
        self.player2Eliminated6.setObjectName("player2Eliminated6")
        self.player2Eliminated4 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Eliminated4.setGeometry(QtCore.QRect(938, 99, 70, 70))
        self.player2Eliminated4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Eliminated4.setText("")
        self.player2Eliminated4.setObjectName("player2Eliminated4")
        self.boardA4 = QtWidgets.QPushButton(self.centralwidget)
        self.boardA4.setGeometry(QtCore.QRect(477, 689, 70, 70))
        self.boardA4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardA4.setText("")
        self.boardA4.setObjectName("boardA4")
        self.boardA7 = QtWidgets.QPushButton(self.centralwidget)
        self.boardA7.setGeometry(QtCore.QRect(697, 689, 70, 70))
        self.boardA7.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardA7.setText("")
        self.boardA7.setObjectName("boardA7")
        self.boardE1 = QtWidgets.QPushButton(self.centralwidget)
        self.boardE1.setGeometry(QtCore.QRect(257, 254, 70, 70))
        self.boardE1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardE1.setText("")
        self.boardE1.setObjectName("boardE1")
        self.boardE4 = QtWidgets.QPushButton(self.centralwidget)
        self.boardE4.setGeometry(QtCore.QRect(477, 250, 70, 70))
        self.boardE4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardE4.setText("")
        self.boardE4.setObjectName("boardE4")
        self.boardE7 = QtWidgets.QPushButton(self.centralwidget)
        self.boardE7.setGeometry(QtCore.QRect(696, 250, 70, 70))
        self.boardE7.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardE7.setText("")
        self.boardE7.setObjectName("boardE7")
        self.player2Bench1 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Bench1.setGeometry(QtCore.QRect(680, 140, 70, 70))
        self.player2Bench1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Bench1.setText("")
        self.player2Bench1.setObjectName("player2Bench1")
        self.player2Bench4 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Bench4.setGeometry(QtCore.QRect(627, 63, 70, 70))
        self.player2Bench4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Bench4.setText("")
        self.player2Bench4.setObjectName("player2Bench4")
        self.player2Bench2 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Bench2.setGeometry(QtCore.QRect(578, 139, 70, 70))
        self.player2Bench2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Bench2.setText("")
        self.player2Bench2.setObjectName("player2Bench2")
        self.player2Bench3 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Bench3.setGeometry(QtCore.QRect(477, 140, 70, 70))
        self.player2Bench3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Bench3.setText("")
        self.player2Bench3.setObjectName("player2Bench3")
        self.player2Bench5 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Bench5.setGeometry(QtCore.QRect(527, 64, 70, 70))
        self.player2Bench5.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Bench5.setText("")
        self.player2Bench5.setObjectName("player2Bench5")
        self.player2Bench6 = QtWidgets.QPushButton(self.centralwidget)
        self.player2Bench6.setGeometry(QtCore.QRect(427, 64, 70, 70))
        self.player2Bench6.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Bench6.setText("")
        self.player2Bench6.setObjectName("player2Bench6")
        self.player2US1 = QtWidgets.QPushButton(self.centralwidget)
        self.player2US1.setGeometry(QtCore.QRect(90, 231, 70, 70))
        self.player2US1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2US1.setText("")
        self.player2US1.setObjectName("player2US1")
        self.player2US3 = QtWidgets.QPushButton(self.centralwidget)
        self.player2US3.setGeometry(QtCore.QRect(90, 141, 70, 70))
        self.player2US3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2US3.setText("")
        self.player2US3.setObjectName("player2US3")
        self.player2US2 = QtWidgets.QPushButton(self.centralwidget)
        self.player2US2.setGeometry(QtCore.QRect(15, 189, 70, 70))
        self.player2US2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2US2.setText("")
        self.player2US2.setObjectName("player2US2")
        self.player2US4 = QtWidgets.QPushButton(self.centralwidget)
        self.player2US4.setGeometry(QtCore.QRect(15, 99, 70, 70))
        self.player2US4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2US4.setText("")
        self.player2US4.setObjectName("player2US4")
        self.player2US6 = QtWidgets.QPushButton(self.centralwidget)
        self.player2US6.setGeometry(QtCore.QRect(15, 11, 70, 70))
        self.player2US6.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2US6.setText("")
        self.player2US6.setObjectName("player2US6")
        self.player2US5 = QtWidgets.QPushButton(self.centralwidget)
        self.player2US5.setGeometry(QtCore.QRect(90, 54, 70, 70))
        self.player2US5.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2US5.setText("")
        self.player2US5.setObjectName("player2US5")
        self.player1PC1 = QtWidgets.QPushButton(self.centralwidget)
        self.player1PC1.setGeometry(QtCore.QRect(609, 799, 70, 70))
        self.player1PC1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1PC1.setText("")
        self.player1PC1.setObjectName("player1PC1")
        self.player1PC2 = QtWidgets.QPushButton(self.centralwidget)
        self.player1PC2.setGeometry(QtCore.QRect(691, 799, 70, 70))
        self.player1PC2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1PC2.setText("")
        self.player1PC2.setObjectName("player1PC2")
        self.boardE2 = QtWidgets.QPushButton(self.centralwidget)
        self.boardE2.setGeometry(QtCore.QRect(330, 250, 70, 70))
        self.boardE2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardE2.setText("")
        self.boardE2.setObjectName("boardE2")
        self.boardE3 = QtWidgets.QPushButton(self.centralwidget)
        self.boardE3.setGeometry(QtCore.QRect(403, 250, 70, 70))
        self.boardE3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardE3.setText("")
        self.boardE3.setObjectName("boardE3")
        self.boardE5 = QtWidgets.QPushButton(self.centralwidget)
        self.boardE5.setGeometry(QtCore.QRect(550, 250, 70, 70))
        self.boardE5.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardE5.setText("")
        self.boardE5.setObjectName("boardE5")
        self.boardE6 = QtWidgets.QPushButton(self.centralwidget)
        self.boardE6.setGeometry(QtCore.QRect(624, 250, 70, 70))
        self.boardE6.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardE6.setText("")
        self.boardE6.setObjectName("boardE6")
        self.boardD3 = QtWidgets.QPushButton(self.centralwidget)
        self.boardD3.setGeometry(QtCore.QRect(477, 372, 70, 70))
        self.boardD3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardD3.setText("")
        self.boardD3.setObjectName("boardD3")
        self.boardD4 = QtWidgets.QPushButton(self.centralwidget)
        self.boardD4.setGeometry(QtCore.QRect(590, 372, 70, 70))
        self.boardD4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardD4.setText("")
        self.boardD4.setObjectName("boardD4")
        self.boardC3 = QtWidgets.QPushButton(self.centralwidget)
        self.boardC3.setGeometry(QtCore.QRect(590, 469, 70, 70))
        self.boardC3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardC3.setText("")
        self.boardC3.setObjectName("boardC3")
        self.boardB4 = QtWidgets.QPushButton(self.centralwidget)
        self.boardB4.setGeometry(QtCore.QRect(590, 568, 70, 70))
        self.boardB4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardB4.setText("")
        self.boardB4.setObjectName("boardB4")
        self.boardD2 = QtWidgets.QPushButton(self.centralwidget)
        self.boardD2.setGeometry(QtCore.QRect(365, 372, 70, 70))
        self.boardD2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardD2.setText("")
        self.boardD2.setObjectName("boardD2")
        self.boardC2 = QtWidgets.QPushButton(self.centralwidget)
        self.boardC2.setGeometry(QtCore.QRect(365, 469, 70, 70))
        self.boardC2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardC2.setText("")
        self.boardC2.setObjectName("boardC2")
        self.boardB3 = QtWidgets.QPushButton(self.centralwidget)
        self.boardB3.setGeometry(QtCore.QRect(477, 568, 70, 70))
        self.boardB3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardB3.setText("")
        self.boardB3.setObjectName("boardB3")
        self.boardB2 = QtWidgets.QPushButton(self.centralwidget)
        self.boardB2.setGeometry(QtCore.QRect(365, 568, 70, 70))
        self.boardB2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardB2.setText("")
        self.boardB2.setObjectName("boardB2")
        self.boardD1 = QtWidgets.QPushButton(self.centralwidget)
        self.boardD1.setGeometry(QtCore.QRect(257, 372, 70, 70))
        self.boardD1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardD1.setText("")
        self.boardD1.setObjectName("boardD1")
        self.boardC1 = QtWidgets.QPushButton(self.centralwidget)
        self.boardC1.setGeometry(QtCore.QRect(257, 469, 70, 70))
        self.boardC1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardC1.setText("")
        self.boardC1.setObjectName("boardC1")
        self.boardB1 = QtWidgets.QPushButton(self.centralwidget)
        self.boardB1.setGeometry(QtCore.QRect(257, 568, 70, 70))
        self.boardB1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardB1.setText("")
        self.boardB1.setObjectName("boardB1")
        self.boardD5 = QtWidgets.QPushButton(self.centralwidget)
        self.boardD5.setGeometry(QtCore.QRect(696, 372, 70, 70))
        self.boardD5.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardD5.setText("")
        self.boardD5.setObjectName("boardD5")
        self.boardC4 = QtWidgets.QPushButton(self.centralwidget)
        self.boardC4.setGeometry(QtCore.QRect(696, 469, 70, 70))
        self.boardC4.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardC4.setText("")
        self.boardC4.setObjectName("boardC4")
        self.boardB5 = QtWidgets.QPushButton(self.centralwidget)
        self.boardB5.setGeometry(QtCore.QRect(696, 568, 70, 70))
        self.boardB5.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardB5.setText("")
        self.boardB5.setObjectName("boardB5")
        self.boardA6 = QtWidgets.QPushButton(self.centralwidget)
        self.boardA6.setGeometry(QtCore.QRect(624, 689, 70, 70))
        self.boardA6.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardA6.setText("")
        self.boardA6.setObjectName("boardA6")
        self.boardA5 = QtWidgets.QPushButton(self.centralwidget)
        self.boardA5.setGeometry(QtCore.QRect(550, 689, 70, 70))
        self.boardA5.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardA5.setText("")
        self.boardA5.setObjectName("boardA5")
        self.boardA3 = QtWidgets.QPushButton(self.centralwidget)
        self.boardA3.setGeometry(QtCore.QRect(403, 689, 70, 70))
        self.boardA3.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardA3.triggered.
        self.boardA3.setText("")
        self.boardA3.setObjectName("boardA3")
        self.boardA2 = QtWidgets.QPushButton(self.centralwidget)
        self.boardA2.setGeometry(QtCore.QRect(330, 689, 70, 70))
        self.boardA2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.boardA2.setText("")
        self.boardA2.setObjectName("boardA2")
        self.player1Bench6 = QtWidgets.QPushButton(self.centralwidget)
        self.player1Bench6.setGeometry(QtCore.QRect(529, 875, 70, 70))
        self.player1Bench6.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Bench6.setText("")
        self.player1Bench6.setObjectName("player1Bench6")
        self.player2PC1 = QtWidgets.QPushButton(self.centralwidget)
        self.player2PC1.setGeometry(QtCore.QRect(345, 142, 70, 70))
        self.player2PC1.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2PC1.setText("")
        self.player2PC1.setObjectName("player2PC1")
        self.player2PC2 = QtWidgets.QPushButton(self.centralwidget)
        self.player2PC2.setGeometry(QtCore.QRect(264, 141, 70, 70))
        self.player2PC2.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2PC2.setText("")
        self.player2PC2.setObjectName("player2PC2")
        self.player1Plates = QtWidgets.QPushButton(self.centralwidget)
        self.player1Plates.setGeometry(QtCore.QRect(640, 879, 91, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player1Plates.sizePolicy().hasHeightForWidth())
        self.player1Plates.setSizePolicy(sizePolicy)
        self.player1Plates.setAutoFillBackground(False)
        self.player1Plates.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player1Plates.setText("")
        self.player1Plates.setObjectName("player1Plates")
        self.player2Plates = QtWidgets.QPushButton(self.centralwidget)
        self.player2Plates.setGeometry(QtCore.QRect(297, 10, 91, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player2Plates.sizePolicy().hasHeightForWidth())
        self.player2Plates.setSizePolicy(sizePolicy)
        self.player2Plates.setAutoFillBackground(False)
        self.player2Plates.setStyleSheet("QPushButton{\n"
"    border-style: hidden;\n"
"}")
        self.player2Plates.setText("")
        self.player2Plates.setObjectName("player2Plates")
        self.background.raise_()
        self.board_overlay.raise_()
        self.board_overlay3v3.raise_()
        self.Player2Ability.raise_()
        self.Player2End.raise_()
        self.Player1ZGauge.raise_()
        self.Player1ZMove.raise_()
        self.Player1Team.raise_()
        self.Player2Team.raise_()
        self.Player2ZGauge.raise_()
        self.Player1End.raise_()
        self.Player1Ability.raise_()
        self.Player2ZMove.raise_()
        self.BlueForfeitButton.raise_()
        self.RedForfeitButton.raise_()
        self.boardA1.raise_()
        self.player1Eliminated1.raise_()
        self.player1Eliminated3.raise_()
        self.player1Eliminated5.raise_()
        self.player1Eliminated2.raise_()
        self.player1Eliminated4.raise_()
        self.player1Eliminated6.raise_()
        self.player1Bench1.raise_()
        self.player1Bench4.raise_()
        self.player1Bench2.raise_()
        self.player1Bench5.raise_()
        self.player1Bench3.raise_()
        self.player1US1.raise_()
        self.player1US2.raise_()
        self.player1US3.raise_()
        self.player1US4.raise_()
        self.player1US5.raise_()
        self.player1US6.raise_()
        self.player2Eliminated1.raise_()
        self.player2Eliminated2.raise_()
        self.player2Eliminated3.raise_()
        self.player2Eliminated5.raise_()
        self.player2Eliminated6.raise_()
        self.player2Eliminated4.raise_()
        self.boardA4.raise_()
        self.boardA7.raise_()
        self.boardE1.raise_()
        self.boardE4.raise_()
        self.boardE7.raise_()
        self.player2Bench1.raise_()
        self.player2Bench4.raise_()
        self.player2Bench2.raise_()
        self.player2Bench3.raise_()
        self.player2Bench5.raise_()
        self.player2Bench6.raise_()
        self.player2US1.raise_()
        self.player2US3.raise_()
        self.player2US2.raise_()
        self.player2US4.raise_()
        self.player2US6.raise_()
        self.player2US5.raise_()
        self.player1PC1.raise_()
        self.player1PC2.raise_()
        self.boardE2.raise_()
        self.boardE3.raise_()
        self.boardE5.raise_()
        self.boardE6.raise_()
        self.boardD3.raise_()
        self.boardD4.raise_()
        self.boardC3.raise_()
        self.boardB4.raise_()
        self.boardD2.raise_()
        self.boardC2.raise_()
        self.boardB3.raise_()
        self.boardB2.raise_()
        self.boardD1.raise_()
        self.boardC1.raise_()
        self.boardB1.raise_()
        self.boardD5.raise_()
        self.boardC4.raise_()
        self.boardB5.raise_()
        self.boardA6.raise_()
        self.boardA5.raise_()
        self.boardA3.raise_()
        self.boardA2.raise_()
        self.player1Bench6.raise_()
        self.player2PC1.raise_()
        self.player2PC2.raise_()
        self.player1Plates.raise_()
        self.player2Plates.raise_()
        self.boardA1.raise_()
        self.player1Eliminated1.raise_()
        self.player1Eliminated3.raise_()
        self.player1Eliminated5.raise_()
        self.player1Eliminated2.raise_()
        self.player1Eliminated4.raise_()
        self.player1Eliminated6.raise_()
        self.player1Bench1.raise_()
        self.player1Bench4.raise_()
        self.player1Bench2.raise_()
        self.player1Bench5.raise_()
        self.player1Bench3.raise_()
        self.player1US1.raise_()
        self.player1US2.raise_()
        self.player1US3.raise_()
        self.player1US4.raise_()
        self.player1US5.raise_()
        self.player1US6.raise_()
        self.player2Eliminated1.raise_()
        self.player2Eliminated2.raise_()
        self.player2Eliminated3.raise_()
        self.player2Eliminated5.raise_()
        self.player2Eliminated6.raise_()
        self.player2Eliminated4.raise_()
        self.boardA4.raise_()
        self.boardA7.raise_()
        self.boardE1.raise_()
        self.boardE4.raise_()
        self.boardE7.raise_()
        self.player2Bench1.raise_()
        self.player2Bench4.raise_()
        self.player2Bench2.raise_()
        self.player2Bench3.raise_()
        self.player2Bench5.raise_()
        self.player2Bench6.raise_()
        self.player2US1.raise_()
        self.player2US3.raise_()
        self.player2US2.raise_()
        self.player2US4.raise_()
        self.player2US6.raise_()
        self.player2US5.raise_()
        self.player1PC1.raise_()
        self.player1PC2.raise_()
        self.boardE2.raise_()
        self.boardE3.raise_()
        self.boardE5.raise_()
        self.boardE6.raise_()
        self.boardD3.raise_()
        self.boardD4.raise_()
        self.boardC3.raise_()
        self.boardB4.raise_()
        self.boardD2.raise_()
        self.boardC2.raise_()
        self.boardB3.raise_()
        self.boardB2.raise_()
        self.boardD1.raise_()
        self.boardC1.raise_()
        self.boardB1.raise_()
        self.boardD5.raise_()
        self.boardC4.raise_()
        self.boardB5.raise_()
        self.boardA6.raise_()
        self.boardA5.raise_()
        self.boardA3.raise_()
        self.boardA2.raise_()
        self.player1Bench6.raise_()
        self.player2PC1.raise_()
        self.player2PC2.raise_()
        self.player1Plates.raise_()
        self.player2Plates.raise_()
        self.background.raise_()
        self.board_overlay.raise_()
        self.board_overlay3v3.raise_()
        self.Player2Ability.raise_()
        self.Player2End.raise_()
        self.Player1ZGauge.raise_()
        self.Player1ZMove.raise_()
        self.Player1Team.raise_()
        self.Player2Team.raise_()
        self.Player2ZGauge.raise_()
        self.Player1End.raise_()
        self.Player1Ability.raise_()
        self.Player2ZMove.raise_()
        self.BlueForfeitButton.raise_()
        self.RedForfeitButton.raise_()
        PoDuRedux.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PoDuRedux)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        self.menuPoDu_Redux = QtWidgets.QMenu(self.menubar)
        self.menuPoDu_Redux.setObjectName("menuPoDu_Redux")
        self.menuControls = QtWidgets.QMenu(self.menubar)
        self.menuControls.setObjectName("menuControls")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        PoDuRedux.setMenuBar(self.menubar)
        self.actionPokemon_Library = QtWidgets.QAction(PoDuRedux)
        self.actionPokemon_Library.setObjectName("actionPokemon_Library")
        self.actionPlate_Library = QtWidgets.QAction(PoDuRedux)
        self.actionPlate_Library.setObjectName("actionPlate_Library")
        self.actionZ_Move_Reference = QtWidgets.QAction(PoDuRedux)
        self.actionZ_Move_Reference.setObjectName("actionZ_Move_Reference")
        self.actionTeam_Builder = QtWidgets.QAction(PoDuRedux)
        self.actionTeam_Builder.setEnabled(False)
        self.actionTeam_Builder.setObjectName("actionTeam_Builder")
        self.actionSave_Game_Log = QtWidgets.QAction(PoDuRedux)
        self.actionSave_Game_Log.setEnabled(False)
        self.actionSave_Game_Log.setShortcutVisibleInContextMenu(True)
        self.actionSave_Game_Log.setObjectName("actionSave_Game_Log")
        self.actionPlay = QtWidgets.QAction(PoDuRedux)
        self.actionPlay.setEnabled(False)
        self.actionPlay.setShortcutVisibleInContextMenu(False)
        self.actionPlay.setObjectName("actionPlay")
        self.actionRestart = QtWidgets.QAction(PoDuRedux)
        self.actionRestart.setEnabled(False)
        self.actionRestart.setShortcutVisibleInContextMenu(True)
        self.actionRestart.setObjectName("actionRestart")
        self.actionExit = QtWidgets.QAction(PoDuRedux)
        self.actionExit.setShortcutVisibleInContextMenu(True)
        self.actionExit.setObjectName("actionExit")
        self.actionChange_Background = QtWidgets.QAction(PoDuRedux)
        self.actionChange_Background.setEnabled(False)
        self.actionChange_Background.setObjectName("actionChange_Background")
        self.actionRule_Settings = QtWidgets.QAction(PoDuRedux)
        self.actionRule_Settings.setObjectName("actionRule_Settings")
        self.actionClassicMode = QtWidgets.QAction(PoDuRedux)
        self.actionClassicMode.setIconVisibleInMenu(True)
        self.actionClassicMode.setObjectName("actionClassicMode")
        self.actionConnect = QtWidgets.QAction(PoDuRedux)
        self.actionConnect.setEnabled(False)
        self.actionConnect.setObjectName("actionConnect")
        self.action3v3_Mode = QtWidgets.QAction(PoDuRedux)
        self.action3v3_Mode.setObjectName("action3v3_Mode")
        self.actionClassic_Mode = QtWidgets.QAction(PoDuRedux)
        self.actionClassic_Mode.setObjectName("actionClassic_Mode")
        self.actionChat = QtWidgets.QAction(PoDuRedux)
        self.actionChat.setObjectName("actionChat")
        self.actionLibraries = QtWidgets.QAction(PoDuRedux)
        self.actionLibraries.setObjectName("actionLibraries")
        self.menuPoDu_Redux.addAction(self.actionLibraries)
        self.menuPoDu_Redux.addAction(self.actionChat)
        self.menuPoDu_Redux.addAction(self.actionConnect)
        self.menuPoDu_Redux.addAction(self.actionChange_Background)
        self.menuControls.addAction(self.actionPlay)
        self.menuControls.addAction(self.actionRestart)
        self.menuControls.addAction(self.actionSave_Game_Log)
        self.menuControls.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionClassic_Mode)
        self.menuOptions.addAction(self.action3v3_Mode)
        self.menuOptions.addAction(self.actionRule_Settings)
        self.menubar.addAction(self.menuPoDu_Redux.menuAction())
        self.menubar.addAction(self.menuControls.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.retranslateUi(PoDuRedux)
        self.board_overlay3v3.hide()
        self.actionRule_Settings.triggered.connect(self.openRule)
        self.actionChat.triggered.connect(self.openChat)
        self.actionLibraries.triggered.connect(self.openLibrary)
        self.actionClassic_Mode.triggered.connect(self.board_overlay3v3.hide)
        self.actionClassic_Mode.triggered.connect(self.board_overlay.show)
        self.actionExit.triggered.connect(PoDuRedux.close)
        self.action3v3_Mode.triggered.connect(self.board_overlay.hide)
        self.action3v3_Mode.triggered.connect(self.board_overlay3v3.show)
        QtCore.QMetaObject.connectSlotsByName(PoDuRedux)
        PoDuRedux.setTabOrder(self.Player1Team, self.Player1Ability)
        PoDuRedux.setTabOrder(self.Player1Ability, self.Player1ZMove)
        PoDuRedux.setTabOrder(self.Player1ZMove, self.Player1End)
        PoDuRedux.setTabOrder(self.Player1End, self.Player2Team)
        PoDuRedux.setTabOrder(self.Player2Team, self.Player2Ability)
        PoDuRedux.setTabOrder(self.Player2Ability, self.Player2ZMove)
        PoDuRedux.setTabOrder(self.Player2ZMove, self.Player2End)

    def retranslateUi(self, PoDuRedux):
        _translate = QtCore.QCoreApplication.translate
        PoDuRedux.setWindowTitle(_translate("PoDuRedux", "PoDu Redux v0.0.0"))
        self.Player1Team.setItemText(0, _translate("PoDuRedux", "Blue Team Select..."))
        self.Player2Team.setItemText(0, _translate("PoDuRedux", "Red Team Select..."))
        self.Player2Ability.setText(_translate("PoDuRedux", "Ability"))
        self.Player1ZGauge.setFormat(_translate("PoDuRedux", "Z-Move %v/36"))
        self.Player2ZGauge.setFormat(_translate("PoDuRedux", "Z-Move: %v/36"))
        self.Player1Ability.setText(_translate("PoDuRedux", "Ability"))
        self.Player1End.setText(_translate("PoDuRedux", "End Turn"))
        self.Player2End.setText(_translate("PoDuRedux", "End Turn"))
        self.Player1ZMove.setText(_translate("PoDuRedux", "Z-Move"))
        self.Player2ZMove.setText(_translate("PoDuRedux", "Z-Move"))
        self.BlueForfeitButton.setText(_translate("PoDuRedux", "Blue Forfeit"))
        self.RedForfeitButton.setText(_translate("PoDuRedux", "Red Forfeit"))
        self.menuPoDu_Redux.setTitle(_translate("PoDuRedux", "Main Menu"))
        self.menuControls.setTitle(_translate("PoDuRedux", "Controls"))
        self.menuOptions.setTitle(_translate("PoDuRedux", "Options"))
        self.actionPokemon_Library.setText(_translate("PoDuRedux", "Pokemon Library"))
        self.actionPlate_Library.setText(_translate("PoDuRedux", "Plate Library"))
        self.actionZ_Move_Reference.setText(_translate("PoDuRedux", "Z-Move Reference"))
        self.actionTeam_Builder.setText(_translate("PoDuRedux", "Team Builder"))
        self.actionSave_Game_Log.setText(_translate("PoDuRedux", "Save Log"))
        self.actionSave_Game_Log.setShortcut(_translate("PoDuRedux", "Ctrl+S"))
        self.actionPlay.setText(_translate("PoDuRedux", "Play"))
        self.actionRestart.setText(_translate("PoDuRedux", "Restart"))
        self.actionRestart.setShortcut(_translate("PoDuRedux", "F5"))
        self.actionExit.setText(_translate("PoDuRedux", "Exit"))
        self.actionExit.setShortcut(_translate("PoDuRedux", "Esc"))
        self.actionChange_Background.setText(_translate("PoDuRedux", "Change Background"))
        self.actionRule_Settings.setText(_translate("PoDuRedux", "Rule Settings"))
        self.actionClassicMode.setText(_translate("PoDuRedux", "Classic Mode"))
        self.actionConnect.setText(_translate("PoDuRedux", "Connect..."))
        self.action3v3_Mode.setText(_translate("PoDuRedux", "3v3 Mode"))
        self.actionClassic_Mode.setText(_translate("PoDuRedux", "Classic Mode"))
        self.actionChat.setText(_translate("PoDuRedux", "Chat"))
        self.actionLibraries.setText(_translate("PoDuRedux", "Libraries"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PoDuRedux = QtWidgets.QMainWindow()
    ui = Ui_PoDuRedux()
    ui.setupUi(PoDuRedux)
    PoDuRedux.show()
    sys.exit(app.exec_())
