# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from Library_Window import Ui_Figure_Library
from LogChat_Window import Ui_Chat
from Rule_Window import Ui_Rule

class Ui_PoDuRedux(object):
    def openLibrary(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Figure_Library()
        self.ui.setupUi(self.window)
        self.window.show()
    def openChat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Chat()
        self.ui.setupUi(self.window)
        self.window.show()
    def openRule(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Rule()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, PoDuRedux):
        PoDuRedux.setObjectName("PoDuRedux")
        PoDuRedux.resize(1024, 1024)
        PoDuRedux.setMouseTracking(True)
        PoDuRedux.setAutoFillBackground(False)
        PoDuRedux.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(PoDuRedux)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget{background-image: url(\'/images/board/backgrounds/Lapis.png\')}")
        self.centralwidget.setObjectName("centralwidget")
        self.Player1Team = QtWidgets.QComboBox(self.centralwidget)
        self.Player1Team.setGeometry(QtCore.QRect(20, 500, 211, 22))
        self.Player1Team.setObjectName("Player1Team")
        self.Player1Team.addItem("")
        self.Player2Team = QtWidgets.QComboBox(self.centralwidget)
        self.Player2Team.setGeometry(QtCore.QRect(790, 500, 221, 22))
        self.Player2Team.setObjectName("Player2Team")
        self.Player2Team.addItem("")
        self.Player2Ability = QtWidgets.QPushButton(self.centralwidget)
        self.Player2Ability.setEnabled(False)
        self.Player2Ability.setGeometry(QtCore.QRect(790, 580, 61, 28))
        self.Player2Ability.setObjectName("Player2Ability")
        self.Player1ZGauge = QtWidgets.QProgressBar(self.centralwidget)
        self.Player1ZGauge.setGeometry(QtCore.QRect(20, 540, 211, 23))
        self.Player1ZGauge.setAutoFillBackground(True)
        self.Player1ZGauge.setMaximum(36)
        self.Player1ZGauge.setProperty("value", 0)
        self.Player1ZGauge.setAlignment(QtCore.Qt.AlignCenter)
        self.Player1ZGauge.setTextVisible(True)
        self.Player1ZGauge.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Player1ZGauge.setObjectName("Player1ZGauge")
        self.Player2ZGauge = QtWidgets.QProgressBar(self.centralwidget)
        self.Player2ZGauge.setGeometry(QtCore.QRect(790, 540, 221, 23))
        self.Player2ZGauge.setAutoFillBackground(True)
        self.Player2ZGauge.setStyleSheet("")
        self.Player2ZGauge.setMaximum(36)
        self.Player2ZGauge.setProperty("value", 0)
        self.Player2ZGauge.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Player2ZGauge.setTextVisible(True)
        self.Player2ZGauge.setInvertedAppearance(True)
        self.Player2ZGauge.setObjectName("Player2ZGauge")
        self.Player1Ability = QtWidgets.QPushButton(self.centralwidget)
        self.Player1Ability.setEnabled(False)
        self.Player1Ability.setGeometry(QtCore.QRect(20, 580, 61, 28))
        self.Player1Ability.setObjectName("Player1Ability")
        self.Player1End = QtWidgets.QPushButton(self.centralwidget)
        self.Player1End.setEnabled(False)
        self.Player1End.setGeometry(QtCore.QRect(172, 580, 61, 28))
        self.Player1End.setObjectName("Player1End")
        self.Player2End = QtWidgets.QPushButton(self.centralwidget)
        self.Player2End.setEnabled(False)
        self.Player2End.setGeometry(QtCore.QRect(942, 580, 71, 28))
        self.Player2End.setObjectName("Player2End")
        self.Player1ZMove = QtWidgets.QPushButton(self.centralwidget)
        self.Player1ZMove.setEnabled(False)
        self.Player1ZMove.setGeometry(QtCore.QRect(90, 580, 71, 28))
        self.Player1ZMove.setObjectName("Player1ZMove")
        self.Player2ZMove = QtWidgets.QPushButton(self.centralwidget)
        self.Player2ZMove.setEnabled(False)
        self.Player2ZMove.setGeometry(QtCore.QRect(860, 580, 71, 28))
        self.Player2ZMove.setObjectName("Player2ZMove")
        self.board_overlay3v3 = QtWidgets.QLabel(self.centralwidget)
        self.board_overlay3v3.setEnabled(True)
        self.board_overlay3v3.setGeometry(QtCore.QRect(0, 0, 1031, 1011))
        self.board_overlay3v3.setText("")
        self.board_overlay3v3.setPixmap(QtGui.QPixmap("images/board/overlays/dueloverlay3v3.png"))
        self.board_overlay3v3.setObjectName("board_overlay3v3")
        self.board_overlay = QtWidgets.QLabel(self.centralwidget)
        self.board_overlay.setEnabled(True)
        self.board_overlay.setGeometry(QtCore.QRect(0, 0, 1031, 1011))
        self.board_overlay.setMouseTracking(False)
        self.board_overlay.setStyleSheet("")
        self.board_overlay.setText("")
        self.board_overlay.setPixmap(QtGui.QPixmap("images/board/overlays/dueloverlay.png"))
        self.board_overlay.setObjectName("board_overlay")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setEnabled(True)
        self.background.setGeometry(QtCore.QRect(0, 0, 1326, 1056))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("images/board/backgrounds/Lapis.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.BlueForfeitButton = QtWidgets.QPushButton(self.centralwidget)
        self.BlueForfeitButton.setGeometry(QtCore.QRect(170, 960, 93, 28))
        self.BlueForfeitButton.setObjectName("BlueForfeitButton")
        self.RedForfeitButton = QtWidgets.QPushButton(self.centralwidget)
        self.RedForfeitButton.setGeometry(QtCore.QRect(770, 960, 93, 28))
        self.RedForfeitButton.setObjectName("RedForfeitButton")
        self.background.raise_()
        self.board_overlay.raise_()
        self.board_overlay3v3.raise_()
        self.Player2Ability.raise_()
        self.Player2End.raise_()
        self.Player1ZGauge.raise_()
        self.Player1ZMove.raise_()
        self.Player1Team.raise_()
        self.Player2Team.raise_()
        self.Player2ZGauge.raise_()
        self.Player1End.raise_()
        self.Player1Ability.raise_()
        self.Player2ZMove.raise_()
        self.BlueForfeitButton.raise_()
        self.RedForfeitButton.raise_()
        PoDuRedux.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PoDuRedux)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        self.menuPoDu_Redux = QtWidgets.QMenu(self.menubar)
        self.menuPoDu_Redux.setObjectName("menuPoDu_Redux")
        self.menuControls = QtWidgets.QMenu(self.menubar)
        self.menuControls.setObjectName("menuControls")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        PoDuRedux.setMenuBar(self.menubar)
        self.actionPokemon_Library = QtWidgets.QAction(PoDuRedux)
        self.actionPokemon_Library.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionPokemon_Library.setObjectName("actionPokemon_Library")
        self.actionPlate_Library = QtWidgets.QAction(PoDuRedux)
        self.actionPlate_Library.setObjectName("actionPlate_Library")
        self.actionZ_Move_Reference = QtWidgets.QAction(PoDuRedux)
        self.actionZ_Move_Reference.setObjectName("actionZ_Move_Reference")
        self.actionTeam_Builder = QtWidgets.QAction(PoDuRedux)
        self.actionTeam_Builder.setEnabled(False)
        self.actionTeam_Builder.setObjectName("actionTeam_Builder")
        self.actionSave_Game_Log = QtWidgets.QAction(PoDuRedux)
        self.actionSave_Game_Log.setEnabled(False)
        self.actionSave_Game_Log.setShortcutVisibleInContextMenu(True)
        self.actionSave_Game_Log.setObjectName("actionSave_Game_Log")
        self.actionPlay = QtWidgets.QAction(PoDuRedux)
        self.actionPlay.setEnabled(False)
        self.actionPlay.setShortcutVisibleInContextMenu(False)
        self.actionPlay.setObjectName("actionPlay")
        self.actionRestart = QtWidgets.QAction(PoDuRedux)
        self.actionRestart.setEnabled(False)
        self.actionRestart.setShortcutVisibleInContextMenu(True)
        self.actionRestart.setObjectName("actionRestart")
        self.actionExit = QtWidgets.QAction(PoDuRedux)
        self.actionExit.setShortcutVisibleInContextMenu(True)
        self.actionExit.setObjectName("actionExit")
        self.actionChange_Background = QtWidgets.QAction(PoDuRedux)
        self.actionChange_Background.setEnabled(False)
        self.actionChange_Background.setObjectName("actionChange_Background")
        self.actionRule_Settings = QtWidgets.QAction(PoDuRedux)
        self.actionRule_Settings.setObjectName("actionRule_Settings")
        self.actionClassicMode = QtWidgets.QAction(PoDuRedux)
        self.actionClassicMode.setIconVisibleInMenu(True)
        self.actionClassicMode.setObjectName("actionClassicMode")
        self.actionRule_Settings_2 = QtWidgets.QAction(PoDuRedux)
        self.actionRule_Settings_2.setObjectName("actionRule_Settings_2")
        self.actionConnect = QtWidgets.QAction(PoDuRedux)
        self.actionConnect.setEnabled(False)
        self.actionConnect.setObjectName("actionConnect")
        self.action3v3_Mode = QtWidgets.QAction(PoDuRedux)
        self.action3v3_Mode.setObjectName("action3v3_Mode")
        self.actionPokemon_Library_3 = QtWidgets.QAction(PoDuRedux)
        self.actionPokemon_Library_3.setObjectName("actionPokemon_Library_3")
        self.actionClassic_Mode = QtWidgets.QAction(PoDuRedux)
        self.actionClassic_Mode.setObjectName("actionClassic_Mode")
        self.actionChat = QtWidgets.QAction(PoDuRedux)
        self.actionChat.setObjectName("actionChat")
        self.actionLibraries = QtWidgets.QAction(PoDuRedux)
        self.actionLibraries.setObjectName("actionLibraries")
        self.menuPoDu_Redux.addAction(self.actionLibraries)
        self.menuPoDu_Redux.addAction(self.actionChat)
        self.menuPoDu_Redux.addAction(self.actionConnect)
        self.menuPoDu_Redux.addAction(self.actionChange_Background)
        self.menuControls.addAction(self.actionPlay)
        self.menuControls.addAction(self.actionRestart)
        self.menuControls.addAction(self.actionSave_Game_Log)
        self.menuControls.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionClassic_Mode)
        self.menuOptions.addAction(self.action3v3_Mode)
        self.menuOptions.addAction(self.actionRule_Settings_2)
        self.menubar.addAction(self.menuPoDu_Redux.menuAction())
        self.menubar.addAction(self.menuControls.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(PoDuRedux)
        self.board_overlay3v3.hide()
        self.actionRule_Settings_2.triggered.connect(self.openRule)
        self.actionChat.triggered.connect(self.openChat)
        self.actionLibraries.triggered.connect(self.openLibrary)
        self.actionClassic_Mode.triggered.connect(self.board_overlay3v3.hide)
        self.actionClassic_Mode.triggered.connect(self.board_overlay.show)
        self.actionExit.triggered.connect(PoDuRedux.close)
        self.action3v3_Mode.triggered.connect(self.board_overlay.hide)
        self.action3v3_Mode.triggered.connect(self.board_overlay3v3.show)
        QtCore.QMetaObject.connectSlotsByName(PoDuRedux)
        PoDuRedux.setTabOrder(self.Player1Team, self.Player1Ability)
        PoDuRedux.setTabOrder(self.Player1Ability, self.Player1ZMove)
        PoDuRedux.setTabOrder(self.Player1ZMove, self.Player1End)
        PoDuRedux.setTabOrder(self.Player1End, self.Player2Team)
        PoDuRedux.setTabOrder(self.Player2Team, self.Player2Ability)
        PoDuRedux.setTabOrder(self.Player2Ability, self.Player2ZMove)
        PoDuRedux.setTabOrder(self.Player2ZMove, self.Player2End)

    def retranslateUi(self, PoDuRedux):
        _translate = QtCore.QCoreApplication.translate
        PoDuRedux.setWindowTitle(_translate("PoDuRedux", "PoDu Redux v0.0.0"))
        self.Player1Team.setItemText(0, _translate("PoDuRedux", "Blue Team Select..."))
        self.Player2Team.setItemText(0, _translate("PoDuRedux", "Red Team Select..."))
        self.Player2Ability.setText(_translate("PoDuRedux", "Ability"))
        self.Player1ZGauge.setFormat(_translate("PoDuRedux", "Z-Move %v/36"))
        self.Player2ZGauge.setFormat(_translate("PoDuRedux", "Z-Move: %v/36"))
        self.Player1Ability.setText(_translate("PoDuRedux", "Ability"))
        self.Player1End.setText(_translate("PoDuRedux", "End Turn"))
        self.Player2End.setText(_translate("PoDuRedux", "End Turn"))
        self.Player1ZMove.setText(_translate("PoDuRedux", "Z-Move"))
        self.Player2ZMove.setText(_translate("PoDuRedux", "Z-Move"))
        self.BlueForfeitButton.setText(_translate("PoDuRedux", "Blue Forfeit"))
        self.RedForfeitButton.setText(_translate("PoDuRedux", "Red Forfeit"))
        self.menuPoDu_Redux.setTitle(_translate("PoDuRedux", "Main Menu"))
        self.menuControls.setTitle(_translate("PoDuRedux", "Controls"))
        self.menuOptions.setTitle(_translate("PoDuRedux", "Options"))
        self.actionPokemon_Library.setText(_translate("PoDuRedux", "Pokemon Library"))
        self.actionPlate_Library.setText(_translate("PoDuRedux", "Plate Library"))
        self.actionZ_Move_Reference.setText(_translate("PoDuRedux", "Z-Move Reference"))
        self.actionTeam_Builder.setText(_translate("PoDuRedux", "Team Builder"))
        self.actionSave_Game_Log.setText(_translate("PoDuRedux", "Save Log"))
        self.actionSave_Game_Log.setShortcut(_translate("PoDuRedux", "Ctrl+S"))
        self.actionPlay.setText(_translate("PoDuRedux", "Play"))
        self.actionRestart.setText(_translate("PoDuRedux", "Restart"))
        self.actionRestart.setShortcut(_translate("PoDuRedux", "F5"))
        self.actionExit.setText(_translate("PoDuRedux", "Exit"))
        self.actionExit.setShortcut(_translate("PoDuRedux", "Esc"))
        self.actionChange_Background.setText(_translate("PoDuRedux", "Change Background"))
        self.actionRule_Settings.setText(_translate("PoDuRedux", "Rule Settings"))
        self.actionClassicMode.setText(_translate("PoDuRedux", "Classic Mode"))
        self.actionRule_Settings_2.setText(_translate("PoDuRedux", "Rule Settings"))
        self.actionConnect.setText(_translate("PoDuRedux", "Connect..."))
        self.action3v3_Mode.setText(_translate("PoDuRedux", "3v3 Mode"))
        self.actionPokemon_Library_3.setText(_translate("PoDuRedux", "Pokemon Library"))
        self.actionClassic_Mode.setText(_translate("PoDuRedux", "Classic Mode"))
        self.actionChat.setText(_translate("PoDuRedux", "Chat"))
        self.actionLibraries.setText(_translate("PoDuRedux", "Libraries"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PoDuRedux = QtWidgets.QMainWindow()
    ui = Ui_PoDuRedux()
    ui.setupUi(PoDuRedux)
    PoDuRedux.show()
    sys.exit(app.exec_())
