# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TeamMetrics_Metrics.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Metrics(object):
    def setupUi(self, Metrics):
        Metrics.setObjectName("Metrics")
        Metrics.resize(310, 747)
        self.label = QtWidgets.QLabel(Metrics)
        self.label.setGeometry(QtCore.QRect(100, 10, 80, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Metrics)
        self.pushButton.setGeometry(QtCore.QRect(40, 700, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Metrics)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 700, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(Metrics)
        self.widget.setGeometry(QtCore.QRect(10, 40, 271, 631))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_13)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_14)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_15)
        self.of1MovementPokemonLabel = QtWidgets.QLabel(self.widget)
        self.of1MovementPokemonLabel.setObjectName("of1MovementPokemonLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.of1MovementPokemonLabel)
        self.of1MovementPokemonLineEdit = QtWidgets.QLineEdit(self.widget)
        self.of1MovementPokemonLineEdit.setObjectName("of1MovementPokemonLineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.of1MovementPokemonLineEdit)
        self.of2MovementPokemonLabel = QtWidgets.QLabel(self.widget)
        self.of2MovementPokemonLabel.setObjectName("of2MovementPokemonLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.of2MovementPokemonLabel)
        self.of2MovementPokemonLineEdit = QtWidgets.QLineEdit(self.widget)
        self.of2MovementPokemonLineEdit.setObjectName("of2MovementPokemonLineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.of2MovementPokemonLineEdit)
        self.of3MovementPokemonLabel = QtWidgets.QLabel(self.widget)
        self.of3MovementPokemonLabel.setObjectName("of3MovementPokemonLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.of3MovementPokemonLabel)
        self.of3MovementPokemonLineEdit = QtWidgets.QLineEdit(self.widget)
        self.of3MovementPokemonLineEdit.setObjectName("of3MovementPokemonLineEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.of3MovementPokemonLineEdit)
        self.of0MovementPokemonLabel = QtWidgets.QLabel(self.widget)
        self.of0MovementPokemonLabel.setObjectName("of0MovementPokemonLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.of0MovementPokemonLabel)
        self.of0MovementPokemonLineEdit = QtWidgets.QLineEdit(self.widget)
        self.of0MovementPokemonLineEdit.setObjectName("of0MovementPokemonLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.of0MovementPokemonLineEdit)
        self.averageDamageLabel = QtWidgets.QLabel(self.widget)
        self.averageDamageLabel.setObjectName("averageDamageLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.averageDamageLabel)
        self.averageDamageLineEdit = QtWidgets.QLineEdit(self.widget)
        self.averageDamageLineEdit.setObjectName("averageDamageLineEdit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.averageDamageLineEdit)
        self.averageStarsLabel = QtWidgets.QLabel(self.widget)
        self.averageStarsLabel.setObjectName("averageStarsLabel")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.averageStarsLabel)
        self.averageStarsLineEdit = QtWidgets.QLineEdit(self.widget)
        self.averageStarsLineEdit.setObjectName("averageStarsLineEdit")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.averageStarsLineEdit)
        self.highestDamageLabel = QtWidgets.QLabel(self.widget)
        self.highestDamageLabel.setObjectName("highestDamageLabel")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.highestDamageLabel)
        self.highestDamageLineEdit = QtWidgets.QLineEdit(self.widget)
        self.highestDamageLineEdit.setObjectName("highestDamageLineEdit")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.highestDamageLineEdit)
        self.lowestDamageLabel = QtWidgets.QLabel(self.widget)
        self.lowestDamageLabel.setObjectName("lowestDamageLabel")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.lowestDamageLabel)
        self.lowestDamageLineEdit = QtWidgets.QLineEdit(self.widget)
        self.lowestDamageLineEdit.setObjectName("lowestDamageLineEdit")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lowestDamageLineEdit)
        self.ofPokemonWWhiteLabel = QtWidgets.QLabel(self.widget)
        self.ofPokemonWWhiteLabel.setObjectName("ofPokemonWWhiteLabel")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.ofPokemonWWhiteLabel)
        self.ofPokemonWWhiteLineEdit = QtWidgets.QLineEdit(self.widget)
        self.ofPokemonWWhiteLineEdit.setObjectName("ofPokemonWWhiteLineEdit")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.ofPokemonWWhiteLineEdit)
        self.ofPokemonWGoldLabel = QtWidgets.QLabel(self.widget)
        self.ofPokemonWGoldLabel.setObjectName("ofPokemonWGoldLabel")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.ofPokemonWGoldLabel)
        self.ofPokemonWGoldLineEdit = QtWidgets.QLineEdit(self.widget)
        self.ofPokemonWGoldLineEdit.setObjectName("ofPokemonWGoldLineEdit")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.ofPokemonWGoldLineEdit)
        self.ofPokemonWPurpleLabel = QtWidgets.QLabel(self.widget)
        self.ofPokemonWPurpleLabel.setObjectName("ofPokemonWPurpleLabel")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.ofPokemonWPurpleLabel)
        self.ofPokemonWPurpleLineEdit = QtWidgets.QLineEdit(self.widget)
        self.ofPokemonWPurpleLineEdit.setObjectName("ofPokemonWPurpleLineEdit")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.ofPokemonWPurpleLineEdit)
        self.ofPokemonWithBlueLabel = QtWidgets.QLabel(self.widget)
        self.ofPokemonWithBlueLabel.setObjectName("ofPokemonWithBlueLabel")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.ofPokemonWithBlueLabel)
        self.ofPokemonWithBlueLineEdit = QtWidgets.QLineEdit(self.widget)
        self.ofPokemonWithBlueLineEdit.setObjectName("ofPokemonWithBlueLineEdit")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.ofPokemonWithBlueLineEdit)
        self.ofPokemonWithMissLabel = QtWidgets.QLabel(self.widget)
        self.ofPokemonWithMissLabel.setObjectName("ofPokemonWithMissLabel")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.ofPokemonWithMissLabel)
        self.ofPokemonWithMissLineEdit = QtWidgets.QLineEdit(self.widget)
        self.ofPokemonWithMissLineEdit.setObjectName("ofPokemonWithMissLineEdit")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.ofPokemonWithMissLineEdit)
        self.teamNameLabel = QtWidgets.QLabel(self.widget)
        self.teamNameLabel.setObjectName("teamNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.teamNameLabel)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.teamNameLineEdit = QtWidgets.QLineEdit(self.widget)
        self.teamNameLineEdit.setObjectName("teamNameLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.teamNameLineEdit)

        self.retranslateUi(Metrics)
        QtCore.QMetaObject.connectSlotsByName(Metrics)

    def retranslateUi(self, Metrics):
        _translate = QtCore.QCoreApplication.translate
        Metrics.setWindowTitle(_translate("Metrics", "Metrics"))
        self.label.setText(_translate("Metrics", "Team Metrics"))
        self.pushButton.setText(_translate("Metrics", "Refresh"))
        self.pushButton_2.setText(_translate("Metrics", "Close"))
        self.label_11.setText(_translate("Metrics", "# of Stage 1 Evolutions:"))
        self.label_12.setText(_translate("Metrics", "# of Stage 2 Evolutions:"))
        self.label_13.setText(_translate("Metrics", "# of Mega Evolutions:"))
        self.label_14.setText(_translate("Metrics", "# of Form Changes:"))
        self.label_15.setText(_translate("Metrics", "Average Movement:"))
        self.of1MovementPokemonLabel.setText(_translate("Metrics", "# of 1 Movement Pokemon:"))
        self.of2MovementPokemonLabel.setText(_translate("Metrics", "# of 2 Movement Pokemon:"))
        self.of3MovementPokemonLabel.setText(_translate("Metrics", "# of 3 Movement Pokemon:"))
        self.of0MovementPokemonLabel.setText(_translate("Metrics", "# of 0 Movement Pokemon:"))
        self.averageDamageLabel.setText(_translate("Metrics", "Average Damage"))
        self.averageStarsLabel.setText(_translate("Metrics", "Average Stars"))
        self.highestDamageLabel.setText(_translate("Metrics", "Highest Damage"))
        self.lowestDamageLabel.setText(_translate("Metrics", "Lowest Damage"))
        self.ofPokemonWWhiteLabel.setText(_translate("Metrics", "# of Pokemon w/ White"))
        self.ofPokemonWGoldLabel.setText(_translate("Metrics", "# of Pokemon w/ Gold"))
        self.ofPokemonWPurpleLabel.setText(_translate("Metrics", "# of Pokemon w/ Purple"))
        self.ofPokemonWithBlueLabel.setText(_translate("Metrics", "# of Pokemon w/ Blue"))
        self.ofPokemonWithMissLabel.setText(_translate("Metrics", "# of Pokemon w/ Miss"))
        self.teamNameLabel.setText(_translate("Metrics", "Team Name:"))
        self.label_10.setText(_translate("Metrics", "# of Types:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Metrics = QtWidgets.QDialog()
    ui = Ui_Metrics()
    ui.setupUi(Metrics)
    Metrics.show()
    sys.exit(app.exec_())
